export { default as ElementAssociations, type ElementAssociationsProps } from '@/features/student/associations/components/composites/ElementAssociations/ElementAssociations.vue'
export { default as AssociateModal, type AssociateModalProps } from '@/features/student/associations/components/overlays/modals/AssociateModal/AssociateModal.vue'
export { default as DeleteAssociationsModal, type DeleteAssociationsModalProps } from '@/features/student/associations/components/overlays/modals/DeleteAssociationsModal/DeleteAssociationsModal.vue'
export { default as AssociationSelectionSection, type AssociationSelectionSectionProps } from '@/features/student/associations/components/sections/AssociationSelectionSection/AssociationSelectionSection.vue'
export { useAssociationSelections } from '@/features/student/associations/composables/use-association-selections/use-association-selections'
export { ASSOCIATION_PAIRS } from '@/features/student/associations/constants/associations.constants'
export type { Association, AssociationLimits, AssociationSelections } from '@/features/student/associations/types/associations.types'
export { countElementAssociations, getAssociableContextTypes } from '@/features/student/associations/utils/associations.utils'
