export const RI_ICONS = {
  ACCOUNT_CIRCLE: 'ri:account-circle-line',
  ARROW_LEFT_RIGHT: 'ri:arrow-left-right-line',
  ATTACHEMENT: 'ri:attachment-line',
  AWARD: 'ri:award-line',
  CHAT: 'ri:chat-4-line',
  DRAFT: 'ri:draft-line',
  HOME: 'ri:home-4-line',
  FILE_TEXT: 'ri:file-text-line',
  LOADER: 'ri:loader-4-line',
  LOCK: 'ri:lock-line',
  NOTIFICATION_FILL: 'ri:notification-2-fill',
  REFRESH: 'ri:refresh-line',
  RIGHT_ARROW: 'ri:arrow-right-line',
  SEARCH: 'ri:search-line',
  SEEDLING: 'ri:seedling-line',
  SETTINGS: 'ri:settings-5-line',
  SHARE: 'ri:share-line',
  UP_ARROW_FILL: 'ri:arrow-up-fill',
  USER_SETTINGS: 'ri:user-setting-line',
  USER_STAR: 'ri:user-star-line',
}
