export { default as DeclaredSkillLevelBadge } from '@/features/student/declaredSkills/components/badges/DeclaredSkillLevelBadge/DeclaredSkillLevelBadge.vue'
export { default as DeclaredSkillMacroSkillBadge } from '@/features/student/declaredSkills/components/badges/DeclaredSkillMacroSkillBadge/DeclaredSkillMacroSkillBadge.vue'
export { default as DeclaredSkillTypeBadge } from '@/features/student/declaredSkills/components/badges/DeclaredSkillTypeBadge/DeclaredSkillTypeBadge.vue'
export { default as AddDeclaredSkillDrawer } from '@/features/student/declaredSkills/components/overlays/AddDeclaredSkillDrawer/AddDeclaredSkillDrawer.vue'
export { studentProjectDeclaredSkillRoute, studentUpdateDeclaredSkillRoute } from '@/features/student/declaredSkills/routes'
export { useDeclaredSkillsStore } from '@/features/student/declaredSkills/stores/declaredSkills.store'
export { default as DeclaredSkillDetails } from '@/features/student/declaredSkills/views/StudentDeclaredSkillView/components/DeclaredSkillDetails/DeclaredSkillDetails.vue'
