export { default as StudentDeliverablesWidget } from './StudentDeliverablesWidget.vue'
export { default as StudentEventsWidget } from './StudentEventsWidget.vue'
export { default as StudentOverviewWidget } from './StudentOverviewWidget.vue'
export { default as StudentPagesWidget } from './StudentPagesWidget.vue'
export { default as StudentResumesWidget } from './StudentResumesWidget.vue'
export { default as StudentSkillsWidget } from './StudentSkillsWidget.vue'
export { default as StudentTracksWidget } from './StudentTracksWidget.vue'
