export const DECLARED_PROGRAM_TITLE_MAX_LENGTH = 80
export const DECLARED_PROGRAM_DESCRIPTION_MAX_LENGTH = 400
export const DECLARED_PROGRAM_INSTITUTION_MAX_LENGTH = 50
export const DECLARED_PROGRAM_RESULT_MAX_LENGTH = 50
