export const ROUTES = {
  AUTH: {
    ACCESSIBILITY: { name: 'auth-accessibility', path: 'accessibility' },
    CGU: { name: 'auth-cgu', path: 'cgu' },
    COOKIES: { name: 'auth-cookies', path: 'cookies' },
    LOGIN: { name: 'auth-login', path: 'login' },
    PERSONAL_DATA: { name: 'auth-personal-data', path: 'personal-data' },
  },
  STAFF: {
    ACCESSIBILITY: { name: 'staff-accessibility', path: 'accessibility' },
    ACTIVITIES: { name: 'staff-activities', path: 'activities' },
    ACTIVITIES_EDIT_NATIONAL_ACTIVITY: { name: 'staff-activities-edit-national-activity', path: 'activities/:id/edit' },
    ACTIVITY_CATALOG: { name: 'staff-activity-catalog', path: 'activities/:status/:id' },
    CGU: { name: 'staff-cgu', path: 'cgu' },
    COOKIES: { name: 'staff-cookies', path: 'cookies' },
    ACTIVITY_FEEDBACK: { name: 'staff-activity-feedback', path: 'activity-feedback/:feedbackId' },
    HOME: { name: 'staff-home', path: '' },
    PERSONAL_DATA: { name: 'staff-personal-data', path: 'personal-data' },
    STUDENT_TRACKING: {
      ACTIVITY_FEEDBACK: { name: 'staff-student-tracking-activity-feedback', path: 'student-tracking/activity-feedbacks/:feedbackId' },
      FEEDBACKS: { name: 'staff-student-tracking-feedbacks', path: 'student-tracking/feedbacks' },
    },
  },
  STUDENT: {
    ABOUT: { name: 'student-about', path: 'about' },
    ACCESSIBILITY: { name: 'student-accessibility', path: 'accessibility' },
    ACTIVITIES_CATALOG: { name: 'student-activities-catalog', path: 'activities/catalog/:thematic?/:id?' },
    ACTIVITIES: { name: 'student-activities', path: 'activities' },
    ACTIVITY: { name: 'student-activity', path: 'activity/:id' },
    BUILD_PROJECT: { name: 'student-build-project', path: 'project/build-project' },
    CGU: { name: 'student-cgu', path: 'cgu' },
    COOKIES: { name: 'student-cookies', path: 'cookies' },
    DECLARED_EXPERIENCE: { name: 'student-declared-experience', path: 'declared-experience/:id' },
    DECLARED_SKILL: { name: 'student-project-declared-skill', path: 'declared-skill/:id' },
    DELIVERABLES: { name: 'student-deliverables', path: 'deliverables' },
    EVENTS: { name: 'student-events', path: 'events' },
    HOME: { name: 'student-home', path: '' },
    PERSONAL_CAREER_DECLARED_PROGRAM_DETAILED: {
      name: 'personal-career-declared-program-detailed',
      path: 'project/personal-career/declared-programs/:id',
    },
    PERSONAL_CAREER_DECLARED_PROGRAMS: { name: 'personal-career-declared-programs', path: 'declared-programs' },
    PERSONAL_CAREER_EXPERIENCES: { name: 'personal-career-experiences', path: 'experiences' },
    PERSONAL_CAREER_UPDATE_DECLARED_PROGRAM: {
      name: 'personal-career-update-declared-program',
      path: 'project/personal-career/update-declared-programs/:id',
    },
    PERSONAL_CAREER: { name: 'student-project-personal-career', path: 'project/personal-career' },
    PERSONAL_DATA: { name: 'student-personal-data', path: 'personal-data' },
    SELFKNOWLEDGE_CATEGORY: { name: 'student-self-knowledge-category', path: 'project/build-project/self-knowledge/:id' },
    SELFKNOWLEDGE_ELEMENT_UPDATE: {
      name: 'student-self-knowledge-element-update',
      path: 'project/build-project/self-knowledge/:categoryId/:elementId/update',
    },
    SKILLS: { name: 'student-skills', path: 'skills' },
    TOOLS_KIT: { name: 'student-tools-kit', path: 'tools/kit' },
    TOOLS_KIT_ACTIVITIES: { name: 'student-tools-kit-activities', path: 'tools/kit/activities' },
    TOOLS_KIT_ACTIVITY: { name: 'student-tools-kit-activity', path: 'tools/kit/activity/:id' },
    TOOLS_KIT_BUILD_PROJECT: { name: 'student-tools-kit-build-project', path: 'tools/kit/build-project' },
    TOOLS_KIT_DECLARED_PROGRAM: { name: 'student-tools-kit-declared-program', path: 'tools/kit/declared-program/:id' },
    TOOLS_KIT_DECLARED_PROGRAMS: { name: 'student-tools-kit-declared-programs', path: 'tools/kit/declared-programs' },
    TOOLS_KIT_EXPERIENCE: { name: 'student-tools-kit-experience', path: 'tools/kit/experience/:id' },
    TOOLS_KIT_EXPERIENCES: { name: 'student-tools-kit-experiences', path: 'tools/kit/experiences' },
    TOOLS_KIT_PERSONAL_CAREER: { name: 'student-tools-kit-personal-career', path: 'tools/kit/personal-career' },
    TOOLS_KIT_SELFKNOWLEDGE_CATEGORY: { name: 'student-tools-kit-self-knowledge-category', path: 'tools/kit/self-knowledge/:id' },
    TOOLS_KIT_SELFKNOWLEDGE_ELEMENT_UPDATE: {
      name: 'student-tools-kit-self-knowledge-element-update',
      path: 'tools/kit/self-knowledge/:categoryId/:elementId/update',
    },
    TOOLS_KIT_SKILL: { name: 'student-tools-kit-skill', path: 'tools/kit/skill/:id' },
    TOOLS_KIT_SKILLS: { name: 'student-tools-kit-skills', path: 'tools/kit/skills' },
    TOOLS_KIT_TRACE: { name: 'student-tools-kit-trace', path: 'tools/kit/trace/:id' },
    TOOLS_KIT_UPDATE_DECLARED_PROGRAM: { name: 'student-tools-kit-update-declared-program', path: 'tools/kit/update-declared-program/:id' },
    TOOLS_KIT_UPDATE_SKILL: { name: 'student-tools-kit-update-skill', path: 'tools/kit/update-skill/:id' },
    TOOLS_KIT_UPDATE_TRACE: { name: 'student-tools-kit-update-trace', path: 'tools/kit/update-trace/:id' },
    TOOLS_TRACE: { name: 'student-tools-trace', path: 'tools/trace/:id' },
    TOOLS_TRACES: { name: 'student-tools-traces', path: 'tools/traces' },
    TOOLS_UPDATE_TRACE: { name: 'student-tools-update-trace', path: 'tools/update-trace/:id' },
    TRACE: { name: 'student-trace', path: 'trace/:id' },
    UPDATE_DECLARED_EXPERIENCE: { name: 'student-update-declared-experience', path: 'update-declared-experience/:id' },
    UPDATE_DECLARED_SKILL: { name: 'student-update-declared-skill', path: 'update-declared-skill/:id' },
    UPDATE_TRACE: { name: 'student-update-trace', path: 'update-trace/:id' },
    WIDGET_ACTIVITY: { name: 'student-widget-activity', path: 'activity-details/:id' },
    WIDGET_ACTIVITY_CATALOG: { name: 'student-widget-activity-catalog', path: 'activity-details/:thematic/:id' },
  },
} as const

export const studentPersonalCareerRoutes = [
  ROUTES.STUDENT.PERSONAL_CAREER,
  ROUTES.STUDENT.PERSONAL_CAREER_DECLARED_PROGRAMS,
  ROUTES.STUDENT.PERSONAL_CAREER_EXPERIENCES,
  ROUTES.STUDENT.PERSONAL_CAREER_DECLARED_PROGRAM_DETAILED,
  ROUTES.STUDENT.PERSONAL_CAREER_UPDATE_DECLARED_PROGRAM,
]

export const studentActivtiesRoutes = [ROUTES.STUDENT.ACTIVITY, ROUTES.STUDENT.ACTIVITIES, ROUTES.STUDENT.ACTIVITIES_CATALOG]

export const studentSkillsRoutes = [ROUTES.STUDENT.SKILLS, ROUTES.STUDENT.DECLARED_SKILL, ROUTES.STUDENT.UPDATE_DECLARED_SKILL]

export const studentProjectBuildProjectRoutes = [ROUTES.STUDENT.BUILD_PROJECT]
