export const ROUTES = {
  STAFF: {
    ACCESSIBILITY: { name: 'staff-accessibility', path: 'accessibility' },
    ACTIVITIES: { name: 'staff-activities', path: 'activities' },
    COOKIES: { name: 'staff-cookies', path: 'cookies' },
    HOME: { name: 'staff-home', path: '' },
    LEGAL: { name: 'staff-legal', path: 'legal' },
    PERSONAL_DATA: { name: 'staff-personal-data', path: 'personal-data' },
  },
  STUDENT: {
    ABOUT: { name: 'student-about', path: 'about' },
    ACCESSIBILITY: { name: 'student-accessibility', path: 'accessibility' },
    APC_UNAVAILABLE: { name: 'student-apc-unavailable', path: 'apc-unavailable' },
    COOKIES: { name: 'student-cookies', path: 'cookies' },
    DECLARED_EXPERIENCE: { name: 'student-declared-experience', path: 'declared-experience/:id' },
    DECLARED_SKILL: { name: 'student-declared-skill', path: 'declared-skill/:id' },
    DELIVERABLES: { name: 'student-deliverables', path: 'deliverables' },
    EDUCATION_SKILLS: { name: 'student-education-skills', path: 'education/skills' },
    EVENTS: { name: 'student-events', path: 'events' },
    HOME: { name: 'student-home', path: '' },
    LEGAL: { name: 'student-legal', path: 'legal' },
    MAILBOX: { name: 'student-mailbox', path: 'mailbox' },
    NOTIFICATIONS: { name: 'student-notifications', path: 'notifications' },
    PERSONAL_CAREER: { name: 'student-project-personal-career', path: 'project/personal-career', },
    PERSONAL_CAREER_DECLARED_PROGRAM_DETAILED: { name: 'personal-career-declared-program-detailed', path: 'project/personal-career/declared-programs/:id' },
    PERSONAL_CAREER_DECLARED_PROGRAMS: { name: 'personal-career-declared-programs', path: 'declared-programs' },
    PERSONAL_CAREER_EXPERIENCES: { name: 'personal-career-experiences', path: 'experiences' },
    PERSONAL_CAREER_MY_CAREER: { name: 'personal-career-my-career', path: 'my-career' },
    PERSONAL_CAREER_UPDATE_DECLARED_PROGRAM: { name: 'personal-career-update-declared-program', path: 'project/personal-career/update-declared-programs/:id' },
    PERSONAL_DATA: { name: 'student-personal-data', path: 'personal-data' },
    PROJECT_ACTIVITIES: { name: 'student-project-activities', path: 'project/activities' },
    PROJECT_ACTIVITIES_CATALOG: { name: 'student-project-activities-catalog', path: 'project/activities/catalog/:thematic?/:id?' },
    PROJECT_ACTIVITIES_DETAILED: { name: 'student-project-activities-detailed', path: 'project/activities/:id' },
    PROJECT_SKILLS: { name: 'student-project-skills', path: 'project/skills' },
    PROJECT_TRAJECTORIES: { name: 'student-project-trajectories', path: 'project/trajectories' },
    SELFKNOWLEDGE_CATEGORY: { name: 'student-self-knowledge-category', path: 'project/trajectories/self-knowledge/:id' },
    SELFKNOWLEDGE_ELEMENT_UPDATE: { name: 'student-self-knowledge-element-update', path: 'project/trajectories/self-knowledge/:categoryId/:elementId/update' },
    SKILL: { name: 'student-skill', path: 'skill/:id' },
    TOOLS_PAGES: { name: 'student-tools-pages', path: 'tools/pages' },
    TOOLS_RESUMES: { name: 'student-tools-resumes', path: 'tools/resumes' },
    TOOLS_TRACES: { name: 'student-tools-traces', path: 'tools/traces' },
    TRACE: { name: 'student-trace', path: 'trace/:id' },
    UPDATE_DECLARED_EXPERIENCE: { name: 'student-update-declared-experience', path: 'update-declared-experience/:id' },
    UPDATE_DECLARED_SKILL: { name: 'student-update-declared-skill', path: 'update-declared-skill/:id' },
  },
} as const
