export const ROUTES = {
  AUTH: {
    ACCESSIBILITY: { name: 'auth-accessibility', path: 'accessibility' },
    COOKIES: { name: 'auth-cookies', path: 'cookies' },
    LEGAL: { name: 'auth-legal', path: 'legal' },
    LOGIN: { name: 'auth-login', path: 'login' },
    PERSONAL_DATA: { name: 'auth-personal-data', path: 'personal-data' },
  },
  STAFF: {
    ACCESSIBILITY: { name: 'staff-accessibility', path: 'accessibility' },
    ACTIVITIES: { name: 'staff-activities', path: 'activities' },
    ACTIVITIES_EDIT_NATIONAL_ACTIVITY: { name: 'staff-activities-edit-national-activity', path: 'activities/:id/edit' },
    ACTIVITY_CATALOG: { name: 'staff-activity-catalog', path: 'activities/:status/:id' },
    ACTIVITY_FEEDBACKS: { name: 'staff-activity-feedbacks', path: 'activities/:id/feedbacks' },
    COOKIES: { name: 'staff-cookies', path: 'cookies' },
    HOME: { name: 'staff-home', path: '' },
    LEGAL: { name: 'staff-legal', path: 'legal' },
    PERSONAL_DATA: { name: 'staff-personal-data', path: 'personal-data' },
    ACTIVITY_FEEDBACK_DETAILS: { name: 'staff-activity-feedback-details', path: 'activity-feedbacks/:feedbackId' },
    STUDENT_FEEDBACKS: { name: 'staff-student-feedbacks', path: 'student-feedbacks' }
  },
  STUDENT: {
    ABOUT: { name: 'student-about', path: 'about' },
    ACCESSIBILITY: { name: 'student-accessibility', path: 'accessibility' },
    APC_UNAVAILABLE: { name: 'student-apc-unavailable', path: 'apc-unavailable' },
    COOKIES: { name: 'student-cookies', path: 'cookies' },
    DECLARED_EXPERIENCE: { name: 'student-declared-experience', path: 'declared-experience/:id' },
    DELIVERABLES: { name: 'student-deliverables', path: 'deliverables' },
    EDUCATION_SKILL: { name: 'student-education-skill', path: 'education/skill/:id' },
    EDUCATION_SKILLS: { name: 'student-education-skills', path: 'education/skills' },
    EVENTS: { name: 'student-events', path: 'events' },
    HOME: { name: 'student-home', path: '' },
    LEGAL: { name: 'student-legal', path: 'legal' },
    MAILBOX: { name: 'student-mailbox', path: 'mailbox' },
    PERSONAL_CAREER: { name: 'student-project-personal-career', path: 'project/personal-career', },
    PERSONAL_CAREER_DECLARED_PROGRAM_DETAILED: { name: 'personal-career-declared-program-detailed', path: 'project/personal-career/declared-programs/:id' },
    PERSONAL_CAREER_DECLARED_PROGRAMS: { name: 'personal-career-declared-programs', path: 'declared-programs' },
    PERSONAL_CAREER_EXPERIENCES: { name: 'personal-career-experiences', path: 'experiences' },
    PERSONAL_CAREER_MY_CAREER: { name: 'personal-career-my-career', path: 'my-career' },
    PERSONAL_CAREER_UPDATE_DECLARED_PROGRAM: { name: 'personal-career-update-declared-program', path: 'project/personal-career/update-declared-programs/:id' },
    PERSONAL_DATA: { name: 'student-personal-data', path: 'personal-data' },
    PROJECT_ACTIVITIES: { name: 'student-project-activities', path: 'project/activities' },
    PROJECT_ACTIVITIES_CATALOG: { name: 'student-project-activities-catalog', path: 'project/activities/catalog/:thematic?/:id?' },
    PROJECT_ACTIVITIES_DETAILED: { name: 'student-project-activities-detailed', path: 'project/activities/:id/details' },
    PROJECT_DECLARED_SKILL: { name: 'student-project-declared-skill', path: 'project/declared-skill/:id' },
    PROJECT_SKILL: { name: 'student-project-skill', path: 'project/skill/:id' },
    PROJECT_SKILLS: { name: 'student-project-skills', path: 'project/skills' },
    PROJECT_TRAJECTORIES: { name: 'student-project-trajectories', path: 'project/trajectories' },
    SELFKNOWLEDGE_CATEGORY: { name: 'student-self-knowledge-category', path: 'project/trajectories/self-knowledge/:id' },
    SELFKNOWLEDGE_ELEMENT_UPDATE: { name: 'student-self-knowledge-element-update', path: 'project/trajectories/self-knowledge/:categoryId/:elementId/update' },
    SKILL: { name: 'student-skill', path: 'skill/:id' },
    TOOLS_PAGES: { name: 'student-tools-pages', path: 'tools/pages' },
    TOOLS_RESUMES: { name: 'student-tools-resumes', path: 'tools/resumes' },
    TOOLS_TRACES: { name: 'student-tools-traces', path: 'tools/traces' },
    TOOLS_TRACE: { name: 'student-tools-trace', path: 'tools/trace/:id' },
    TOOLS_UPDATE_TRACE: { name: 'student-tools-update-trace', path: 'tools/update-trace/:id' },
    TRACE: { name: 'student-trace', path: 'trace/:id' },
    UPDATE_DECLARED_EXPERIENCE: { name: 'student-update-declared-experience', path: 'update-declared-experience/:id' },
    UPDATE_DECLARED_SKILL: { name: 'student-update-declared-skill', path: 'update-declared-skill/:id' },
    UPDATE_TRACE: { name: 'student-update-trace', path: 'update-trace/:id' },
  },
} as const

export const studentPersonalCareerRoutes = [
  ROUTES.STUDENT.PERSONAL_CAREER,
  ROUTES.STUDENT.PERSONAL_CAREER_MY_CAREER,
  ROUTES.STUDENT.PERSONAL_CAREER_DECLARED_PROGRAMS,
  ROUTES.STUDENT.PERSONAL_CAREER_EXPERIENCES,
  ROUTES.STUDENT.PERSONAL_CAREER_DECLARED_PROGRAM_DETAILED,
  ROUTES.STUDENT.PERSONAL_CAREER_UPDATE_DECLARED_PROGRAM,
]

export const studentProjectActivtiesRoutes = [
  ROUTES.STUDENT.PROJECT_ACTIVITIES,
  ROUTES.STUDENT.PROJECT_ACTIVITIES_CATALOG,
  ROUTES.STUDENT.PROJECT_ACTIVITIES_DETAILED,
]

export const studentProjectTrajectoriesRoutes = [
  ROUTES.STUDENT.PROJECT_TRAJECTORIES,
]
