export const DSFR = {
  BTN_PREFIX: 'fr-btn',
  BTNS_GROUP_PREFIX: 'fr-btns-group',
  CHECKBOX_GROUP_PREFIX: 'fr-checkbox-group',
  FIELDSET_PREFIX: 'fr-fieldset',
  FIELDSET_ELEMENT_PREFIX: 'fr-fieldset__element',
  LINK_PREFIX: 'fr-link',
  MESSAGE_PREFIX: 'fr-message',
  RADIO_PREFIX: 'fr-radio',
  RADIO_GROUP_PREFIX: 'fr-radio-group',
}

export const DSFR_ICONS = {
  ATTACHEMENT: 'fr-icon-attachment-line',
  AWARD: 'fr-icon-award-line',
  DRAFT: 'fr-icon-draft-line',
  HOME: 'fr-icon-home-4-line',
  FILE_TEXT: 'fr-icon-file-text-line',
  REFRESH: 'fr-icon-refresh-line',
  RIGHT_ARROW: 'fr-icon-arrow-right-line',
  SEARCH: 'fr-icon-search-line',
  SEEDLING: 'fr-icon-seedling-line',
  SETTINGS: 'fr-icon-settings-5-line',
  SHARE: 'fr-icon-share-line',
  UP_ARROW_FILL: 'fr-icon-arrow-up-fill',
  USER_SETTINGS: 'fr-icon-user-setting-line',
  USER_STAR: 'fr-icon-user-star-line',
}

export const RI_ICONS = {
  ACCOUNT_CIRCLE: 'ri:account-circle-line',
  ARROW_LEFT_RIGHT: 'ri:arrow-left-right-line',
  ATTACHEMENT: 'ri:attachment-line',
  AWARD: 'ri:award-line',
  CHAT: 'ri:chat-4-line',
  DRAFT: 'ri:draft-line',
  HOME: 'ri:home-4-line',
  FILE_TEXT: 'ri:file-text-line',
  LOCK: 'ri:lock-line',
  NOTIFICATION_FILL: 'ri:notification-2-fill',
  REFRESH: 'ri:refresh-line',
  RIGHT_ARROW: 'ri:arrow-right-line',
  SEARCH: 'ri:search-line',
  SEEDLING: 'ri:seedling-line',
  SETTINGS: 'ri:settings-5-line',
  SHARE: 'ri:share-line',
  UP_ARROW_FILL: 'ri:arrow-up-fill',
  USER_SETTINGS: 'ri:user-setting-line',
  USER_STAR: 'ri:user-star-line',
}
