import { EOS_ICONS, IX_ICONS, MDI_ICONS, MS_ICONS } from '@avenirs-esr/avenirs-dsav'

export const ICONS = {
  ACTIVITY: EOS_ICONS.ACTION_CHAINS_OUTLINED,
  ACTIVITY_PERSPECTIVE: MS_ICONS.FEATURED_PLAY_LIST_OUTLINE,
  ASSOCIATED: MDI_ICONS.DIAMOND_STONE,
  EXPERIENCES: MDI_ICONS.HUB_OUTLINE,
  FUTURES: MDI_ICONS.IMAGE_FILTER_CENTER_FOCUS_WEAK,
  NEW: IX_ICONS.LIBRARY_NEW,
  PROGRAMS: MS_ICONS.BOOKMARK_STAR_OUTLINE,
  RESUMES: MDI_ICONS.FILE_ACCOUNT_OUTLINE,
  SELF_KNOWLEDGE: MDI_ICONS.FAMILY,
  SKILLS: MDI_ICONS.STARS,
  TRACES: MDI_ICONS.ATTACH_FILE,
  TRAJECTORIES: MDI_ICONS.ARROW_DECISION,
  TRANSVERSAL: MDI_ICONS.WARNING // TODO: waiting for Morgane
}
