export enum ProjectActivitiesCatalogThemes {
  NEW = 'NEW',
  SELF_KNOWLEDGE = 'SELF_KNOWLEDGE',
  FUTURES = 'FUTURES',
  COURSES = 'COURSES',
  EXPERIENCES = 'EXPERIENCES',
  TRAJECTORIES = 'TRAJECTORIES',
  RESUMES = 'RESUMES',
  TRANSVERSAL = 'TRANSVERSAL',
}
