import { LINK_MAX_LENGTH } from '@/common/constants'

export const DECLARED_PROGRAM_TITLE_MAX_LENGTH = 80
export const DECLARED_PROGRAM_DESCRIPTION_MAX_LENGTH = 400
export const DECLARED_PROGRAM_ORGANIZATION_MAX_LENGTH = 50
export const DECLARED_PROGRAM_RESULT_MAX_LENGTH = 50
export const DECLARED_PROGRAM_SOURCE_OF_INFORMATION_MAX_LENGTH = 200

export const DECLARED_EXPERIENCE_TITLE_MAX_LENGTH = 80
export const DECLARED_EXPERIENCE_ORGANIZATION_MAX_LENGTH = 80
export const DECLARED_EXPERIENCE_ACTIVITY_SECTOR_MAX_LENGTH = 50
export const DECLARED_EXPERIENCE_LOCATION_MAX_LENGTH = 50
export const DECLARED_EXPERIENCE_SOURCE_OF_INFORMATION_MAX_LENGTH = 200
export const DECLARED_EXPERIENCE_DESCRIPTION_MAX_LENGTH = 400
export const DECLARED_EXPERIENCE_SUMMARY_MAX_LENGTH = 400
export const DECLARED_EXPERIENCE_EXTERNAL_LINK_MAX_LENGTH = LINK_MAX_LENGTH
export const DECLARED_EXPERIENCE_RESULT_MAX_LENGTH = 50
