/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToaster: typeof import('./components/AppToaster.vue')['default']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrBadge: typeof import('@gouvminint/vue-dsfr')['DsfrBadge']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrLanguageSelector: typeof import('@gouvminint/vue-dsfr')['DsfrLanguageSelector']
    DsfrModal: typeof import('@gouvminint/vue-dsfr')['DsfrModal']
    DsfrNavigation: typeof import('@gouvminint/vue-dsfr')['DsfrNavigation']
    DsfrSearchBar: typeof import('@gouvminint/vue-dsfr')['DsfrSearchBar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VIcon: typeof import('@gouvminint/vue-dsfr')['VIcon']
  }
}
