/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DsfrBadge: typeof import('@gouvminint/vue-dsfr')['DsfrBadge']
    DsfrBreadcrumb: typeof import('@gouvminint/vue-dsfr')['DsfrBreadcrumb']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrFooterLink: typeof import('@gouvminint/vue-dsfr')['DsfrFooterLink']
    DsfrFooterPartners: typeof import('@gouvminint/vue-dsfr')['DsfrFooterPartners']
    DsfrLanguageSelector: typeof import('@gouvminint/vue-dsfr')['DsfrLanguageSelector']
    DsfrLogo: typeof import('@gouvminint/vue-dsfr')['DsfrLogo']
    DsfrModal: typeof import('@gouvminint/vue-dsfr')['DsfrModal']
    DsfrNavigation: typeof import('@gouvminint/vue-dsfr')['DsfrNavigation']
    DsfrSearchBar: typeof import('@gouvminint/vue-dsfr')['DsfrSearchBar']
    DsfrTabContent: typeof import('@gouvminint/vue-dsfr')['DsfrTabContent']
    DsfrTabItem: typeof import('@gouvminint/vue-dsfr')['DsfrTabItem']
    DsfrTabs: typeof import('@gouvminint/vue-dsfr')['DsfrTabs']
    DsfrTag: typeof import('@gouvminint/vue-dsfr')['DsfrTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VIcon: typeof import('@gouvminint/vue-dsfr')['VIcon']
  }
}
