export const MDI_ICONS = {
  ACCOUNT_CIRCLE: 'mdi:account-circle-outline',
  ARROW_DECISION: 'mdi:arrow-decision',
  ARROW_RIGHT: 'mdi:arrow-right',
  ARROW_TOP_RIGHT: 'mdi:arrow-top-right-thick',
  ATTACH_FILE: 'mdi:attach-file',
  BELL_NOTIFICATION: 'mdi:bell-notification',
  BRIEFCASE_VARIANT: 'mdi:briefcase-variant-outline',
  CALENDAR_MONTH: 'mdi:calendar-month-outline',
  CHAT_BUBBLE: 'mdi:chat-bubble-outline',
  FILE_ACCOUNT: 'mdi:file-account-outline',
  GRADUATION_CAP: 'mdi:graduation-cap-outline',
  HOME_VARIANT: 'mdi:home-variant-outline',
  LOADING: 'mdi:loading',
  LOGOUT: 'mdi:logout',
  NOTIFICATIONS_NONE: 'mdi:notifications-none',
  PENCIL: 'mdi:pencil-outline',
  POST_IT_NOTES: 'mdi:post-it-notes-outline',
  STAR_SHOOTING: 'mdi:star-shooting-outline',
  STARS: 'mdi:stars',
}
