export const MDI_ICONS = {
  ACCOUNT_CIRCLE: 'mdi:account-circle-outline',
  ALERT_CIRCLE: 'mdi:alert-circle-outline',
  ARROW_DECISION: 'mdi:arrow-decision',
  ARROW_LEFT: 'mdi:arrow-left-thin',
  ARROW_RIGHT: 'mdi:arrow-right-thin',
  ARROW_TOP_RIGHT: 'mdi:arrow-top-right-thick',
  ATTACH_FILE: 'mdi:attach-file',
  BELL_NOTIFICATION: 'mdi:bell-notification',
  BOOK_LOCATION: 'mdi:book-location-outline',
  BRIEFCASE_VARIANT: 'mdi:briefcase-variant-outline',
  CALENDAR_MONTH: 'mdi:calendar-month-outline',
  CHAT_BUBBLE: 'mdi:chat-bubble-outline',
  CHECK: 'mdi:check',
  CHECK_CIRCLE: 'mdi:check-circle',
  CLOSE_CIRCLE: 'mdi:close-circle-outline',
  FILE_ACCOUNT: 'mdi:file-account-outline',
  FILE_DOCUMENT_EDIT: 'mdi:file-document-edit-outline',
  GRADUATION_CAP: 'mdi:graduation-cap-outline',
  HOME_VARIANT: 'mdi:home-variant-outline',
  HOURGLASS: 'mdi:hourglass',
  INFORMATION: 'mdi:information-outline',
  LOADING: 'mdi:loading',
  LOGOUT: 'mdi:logout',
  NOTIFICATIONS_NONE: 'mdi:notifications-none',
  PENCIL: 'mdi:pencil-outline',
  POST_IT_NOTES: 'mdi:post-it-notes-outline',
  SHARE_VARIANT: 'mdi:share-variant-outline',
  STAR_SHOOTING: 'mdi:star-shooting-outline',
  STARS: 'mdi:stars',
  SWAP_HORIZONTAL: 'mdi:swap-horizontal',
  SWAP_VERTICAL_VARIANT: 'mdi:swap-vertical-variant',
  TEST_TUBE_EMPTY: 'mdi:test-tube-empty',
  WARNING: 'mdi:warning-outline'
}

export const RI_ICONS = {
  DICE_1: 'ri:dice-1-line',
  DICE_4: 'ri:dice-4-line',
}
