export const MDI_ICONS = {
  ACCOUNT_CIRCLE_OUTLINE: 'mdi:account-circle-outline',
  ALERT_CIRCLE_OUTLINE: 'mdi:alert-circle-outline',
  ARROW_DECISION: 'mdi:arrow-decision',
  ARROW_LEFT_THIN: 'mdi:arrow-left-thin',
  ARROW_RIGHT_THIN: 'mdi:arrow-right-thin',
  ARROW_TOP_RIGHT_THICK: 'mdi:arrow-top-right-thick',
  ATTACH_FILE: 'mdi:attach-file',
  BELL_NOTIFICATION: 'mdi:bell-notification',
  BOOK_LOCATION_OUTLINE: 'mdi:book-location-outline',
  BRIEFCASE_VARIANT_OUTLINE: 'mdi:briefcase-variant-outline',
  CALENDAR_MONTH_OUTLINE: 'mdi:calendar-month-outline',
  CHAT_BUBBLE_OUTLINE: 'mdi:chat-bubble-outline',
  CHECK: 'mdi:check',
  CHECK_CIRCLE: 'mdi:check-circle',
  CLOSE_CIRCLE_OUTLINE: 'mdi:close-circle-outline',
  FILE_ACCOUNT_OUTLINE: 'mdi:file-account-outline',
  FILE_DOCUMENT_EDIT_OUTLINE: 'mdi:file-document-edit-outline',
  FORMAT_LIST_BULLETED: 'mdi:format-list-bulleted',
  HOME_VARIANT_OUTLINE: 'mdi:home-variant-outline',
  HOURGLASS: 'mdi:hourglass',
  INFORMATION_OUTLINE: 'mdi:information-outline',
  LOADING_OUTLINE: 'mdi:loading',
  LOGOUT: 'mdi:logout',
  NAVIGATE_BEFORE: 'mdi:navigate-before',
  NAVIGATE_NEXT: 'mdi:navigate-next',
  NOTIFICATIONS_NONE: 'mdi:notifications-none',
  PAGE_FIRST: 'mdi:page-first',
  PAGE_LAST: 'mdi:page-last',
  PENCIL_OUTLINE: 'mdi:pencil-outline',
  POST_IT_NOTES_OUTLINE: 'mdi:post-it-notes-outline',
  SHARE_VARIANT_OUTLINE: 'mdi:share-variant-outline',
  STAR_SHOOTING_OUTLINE: 'mdi:star-shooting-outline',
  STARS: 'mdi:stars',
  SWAP_HORIZONTAL: 'mdi:swap-horizontal',
  SWAP_VERTICAL_VARIANT: 'mdi:swap-vertical-variant',
  TEST_TUBE_EMPTY: 'mdi:test-tube-empty',
  WARNING_OUTLINE: 'mdi:warning-outline',
  DOTS_VERTICAL: 'mdi:dots-vertical',
  PLUS_CIRCLE_OUTLINE: 'mdi:plus-circle-outline',
  TRASH_CAN_OUTLINE: 'mdi:trash-can-outline',
}

export const RI_ICONS = {
  DICE_1_LINE: 'ri:dice-1-line',
  DICE_4_LINE: 'ri:dice-4-line',
}
